spring:
  profiles:
    active: dev

---
server:
  port: 8201

#dev配置
spring:
  profiles:
    active: dev
  application:
    name: springcloud-provider-dept

#eureka的客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---
server:
  port: 8202
#test配置
spring:
  profiles:
    active: test
  application:
    name: springcloud-provider-dept

#eureka的客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka





