spring:
  profiles:
    active: test

---
#dev配置
spring:
  profiles:
    active: dev
  application:
    name: springcloud-provider-dept-dev

server:
  port: 8201
  
#eureka的客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---
#test配置
spring:
  profiles:
    active: test
  application:
    name: springcloud-provider-dept-test
    
server:
  port: 8202
  
#eureka的客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka





