server:
  port: 9092

spring:
  application:
    name: springcloud-cloud-zuul



#eureka的客户端配置
eureka:
  client:

    #    监控页面
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  #这服务实例的名字
  instance:
    instance-id: springcloud-zuul-9092
    prefer-ip-address: true

#配置路由网关信息
zuul:
#  设置映射路径
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#  访问前缀
  prefix: /kuang


#服务实例的一些信息
info:
  app.name: jc-springcloud
  company.name: jcbaba

